[workspace]
resolver = "2"
members = ["crates/qga-swarm-convert", "crates/qga-swarm-preview"]

[workspace.package]
edition = "2021"
license = "MIT"

[workspace.dependencies]
qga-gpu = { git = "https://github.com/kinaar8340/qga_gpu", rev = "90aa7fc739d670d1205c0dd8c47f8c2f632e2eff", default-features = false, features = ["headless", "capture"] }
glam = "0.29"
anyhow = "1"
